const CLEAR_COUNTER = 'CLEAR_COUNTER';
const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
const SET_COUNTER = 'SET_COUNTER';

export {
  CLEAR_COUNTER,
  DECREMENT_COUNTER,
  INCREMENT_COUNTER,
  SET_COUNTER,
};
